server:
  port: 8080

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/minettine
    username: minettine
    password: minettine
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      #ddl-auto: create-drop
      ddl-auto: create
      naming:
        # 테이블 및 컬럼명 그대로 사용( 소문자 변환 사용안함 )
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
      # JPA SQL format
      format_sql: true
      dialect: org.hibernate.dialect.MariaDB106Dialect
  h2:
    console:
      enabled: true

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            # JPA value 확인
            sql: trace